### ISSUE TITLE
Move Environment Watermark away from edge of screen & keep it only on log in screen

### ISSUE THREAD

**Issue by sarahdraugelis** [FEMR/fEMR-OnChain-Core#695]
The watermark should appear only on log in screen and should be more centered. This watermark should appear in the dev environment, the training environment, but not the production environment. 

<img width="1440" alt="Screen Shot 2022-03-29 at 2 09 20 PM" src="https://user-images.githubusercontent.com/30377988/160677121-aecf6805-7156-4b00-bcbe-27c6839f6fb2.png">

**Comment by Romulus10** [comment]
Should be fixed.

**Comment by sarahdraugelis** [comment]
<img width="1440" alt="Screen Shot 2022-03-30 at 1 23 49 PM" src="https://user-images.githubusercontent.com/30377988/160894820-7b1375f9-dca8-4d72-b550-60b3b132f530.png">

Still the same on my end here

**Comment by Romulus10** [comment]
This looks like another style caching issue, so I let it sit overnight. How does it look?

**Comment by sarahdraugelis** [comment]
Utterly brilliant.
