### ISSUE TITLE
 Error message upon patient data export

### ISSUE THREAD

**Issue by sarahdraugelis** [FEMR/fEMR-OnChain-Core#701]
<img width="1440" alt="Screen Shot 2022-04-01 at 9 24 58 AM" src="https://user-images.githubusercontent.com/30377988/161272484-92ef12ac-2c94-4578-9fad-a6a8888ca568.png">

Error messages when clicking on "Export Deidentified Patient Data" in Campaign Manager.

**Comment by Romulus10** [comment]
I just pushed these changes to dev.

**Comment by sarahdraugelis** [comment]
<img width="1440" alt="Screen Shot 2022-04-03 at 4 37 17 PM" src="https://user-images.githubusercontent.com/30377988/161447527-513261c6-665a-4a97-a0b3-adb68dc332e7.png">


Still getting an error message
